version: '3'

services:
  envoy:
    container_name: envoy
    build:
      context: .
      dockerfile: ./envoy/Dockerfile
    restart: unless-stopped
    ports:
      - "80:8080"
      - "9901:9901"
      - "10000:10000"
    networks: 
      - chessguru-network
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
  app-production:
    container_name: app-production
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    stdin_open: true 
    ports:
      - 8085:8085
    networks: 
      - chessguru-network

networks:
  chessguru-network:
        # external: true